---
- name: Install package
  hosts: servers
  become: true
  become_method: su
  vars_files:
    - secrets.yml
  vars: 
    ansible_become_pass: '{{ root_password }}'
    
  tasks:
  - name: Update and upgrade
    shell: apt update && apt upgrade -y
  - name: Upgrade
    shell: apt upgrade -y

  - name: Install vim
    package:
     name: vim
     state: latest

  - name: Install git  
    package:
     name: git
     state: latest

  - name: Install tree  
    package:
     name: tree
     state: latest

  - name: Install htop 
    package:
     name: htop
     state: latest

  - name: Install curl  
    package:
     name: curl
     state: latest

  - name: Install emacs  
    package:
     name: emacs
     state: latest

  - name: Install net-tools  
    package:
     name: net-tools
     state: latest

  - name: Install sudo  
    package:
     name: sudo
     state: latest

  - name: Install make  
    package:
     name: make
     state: latest

  - name: Install unzip  
    package:
     name: unzip
     state: latest

  - name: Install python3  
    package:
     name: python3
     state: latest

  - name: Install python3-pip 
    package:
     name: python3-pip
     state: latest