---
- name: Install Composer and execute database migrations
  hosts: servers
  become: true
  become_method: su
  vars_files:
    - secrets.yml
  vars: 
    ansible_become_pass: '{{ root_password }}'
    
  tasks:
  - name: Download Composer
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/composer-setup.php
      mode: 0755
    register: composer_setup

  - name: Install Composer
    shell: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
    when: composer_setup.changed

  - name: Install dependencies
    shell: composer install
    args:
      chdir: /var/www/html/back
      executable: /usr/bin/php

  - name: Execute database migrations
    shell: php artisan migrate:fresh --seed
    args:
      chdir: /var/www/html/back