---
- name: Install Composer and execute database migrations
  hosts: localhost
  become: true
  become_method: su
  vars_files:
    - secrets.yml
  vars: 
    ansible_become_pass: '{{ root_password }}'
    
  tasks:
    - name: Yarn Install 
      shell: yarn install /var/www/html/front/

    - name: ng build
      shell: ng build /var/www/html/front/